name: Ejecutar Notebook con Papermill

on:
  push:
    paths:
      - "notebooks/*.ipynb"
  workflow_dispatch:

jobs:
  train-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar notebook con Papermill
        run: |
          papermill notebooks/train.ipynb notebooks/output_model.ipynb \
            -p learning_rate 0.05 \
            -p n_estimators 200

      - name: Cargar notebook generado como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: output-notebook
          path: notebooks/output_model.ipynb
